### ISSUE TITLE
rostopic not  echo /fix

### ISSUE THREAD

**Issue by subshine** [cggos/imu_gnss_fusion#2]
utbm_robocar_dataset_20180719_noimage.bag  rostopic not  echo /fix,请问您遇到过这种问题吗？
![image](https://user-images.githubusercontent.com/46065970/93066096-2132b300-f6ac-11ea-8b1a-490f47f3d277.png)
![image](https://user-images.githubusercontent.com/46065970/93066131-2d1e7500-f6ac-11ea-8d94-3b8595938964.png)
![image](https://user-images.githubusercontent.com/46065970/93066165-37d90a00-f6ac-11ea-830c-1179cbb0f789.png)

**Comment by cggos** [comment]
没有遇到过，检查一下 `rqt_graph`，看一下 `nmea_navsat_driver` 的输入是否有数据

**Comment by subshine** [comment]
> 没有遇到过，检查一下 `rqt_graph`，看一下 `nmea_navsat_driver` 的输入是否有数据

谢谢，已经解决，是缺少nmea_msgs的消息功能包的问题
